### ISSUE TITLE
User Story Create Wireframes

### ISSUE THREAD

**Issue by craigallendev** [craigallendev/prevent-awareness#2]
As a **developer** i can **design wireframes for the layout of the website** so that **we have a clear path to code the application.**

**Comment by craigallendev** [comment]
[Prevent wireframes.pdf](https://github.com/user-attachments/files/15536090/Prevent.wireframes.pdf)

**Comment by craigallendev** [comment]
https://github.com/craigallendev/prevent-awareness/issues/1#issuecomment-2145427350

**Comment by orechelsea** [comment]
Should we decide on the features we want then from the Balsamiq wireframe and who's gonna take on what task for tomorrow.

**Comment by kjrinuk** [comment]
[Prevent Wireframe - Keith.pdf](https://github.com/user-attachments/files/15536875/Prevent.Wireframe.-.Keith.pdf)

**Comment by kjrinuk** [comment]
https://balsamiq.cloud/svv8qoh/p6g87tj/r9C94

**Comment by craigallendev** [comment]
https://github.com/craigallendev/prevent-awareness/issues/2#issuecomment-2145498248 we have agreed as a team to use this wireframe as our reference for our application
